#!/bin/bash

set -e

my_package=`basename ${PWD}`
my_excludes=".git* make-release .*.swp"

for xcl in ${my_excludes}; do
  tar_cmds="${tar_cmds} --exclude ${xcl}"
done

cd ..
tar cvzf ${my_package}.tar.gz ${tar_cmds} ${my_package}/.
gpg --armor --sign --detach-sig --default-key FA5E6F3E ${my_package}.tar.gz
